In [1]:
import pandas as pd

In [2]:
!ls

Mod4Project.ipynb  Untitled.ipynb     dress_patterns.csv

In [3]:
raw = pd.read_csv('dress_patterns.csv')

In [48]:
raw.shape

(15702, 4)

In [5]:
img_urls = raw['image_url']

In [9]:
img_urls[0]

'http://s3-eu-west-1.amazonaws.com/we-attributes/dress/23/5f635c0fa59f4270a6953f67dcddcda3.jpg.png'

In [39]:
import requests

with open('pic1.png', 'wb') as handle:
        response = requests.get('http://s3-eu-west-1.amazonaws.com/we-attributes/dress/23/5f635c0fa59f4270a6953f67dcddcda3.jpg.png', stream=True)

        if not response.ok:
            print (response)

        for block in response.iter_content(1024):
            if not block:
                break

            handle.write(block)

In [15]:
raw['category'].value_counts()

plain          8385
floral         2776
stripes         701
polka dot       651
OTHER           513
tribal          507
squares         439
ikat            355
animal          352
geometry        342
cartoon         261
scales          112
chevron          96
letter_numb      82
houndstooth      66
stars            45
skull            19
Name: category, dtype: int64

In [50]:
raw_confident_1 = raw[raw['category:confidence']==1]

In [51]:
raw_confident_1.shape

(10339, 4)

In [ ]:
raw_confident_1_remove_others = raw_confident_1['']

In [52]:
raw_confident_1['category'].value_counts()

plain          6722
floral         1879
stripes         500
polka dot       370
squares         269
animal          192
tribal          109
cartoon          52
letter_numb      51
geometry         41
ikat             40
OTHER            34
chevron          27
stars            16
houndstooth      15
scales           12
skull            10
Name: category, dtype: int64

In [16]:
plain_imgs = raw[raw['category']=='plain']

In [19]:
floral_imgs = raw[raw['category']=='floral']
stripes_imgs = raw[raw['category']=='stripes']
polkadot_imgs = raw[raw['category']=='polka dot']
other_imgs = raw[raw['category']=='OTHER']
tribal_imgs = raw[raw['category']=='tribal']
squares_imgs = raw[raw['category']=='squares']
ikat_imgs = raw[raw['category']=='ikat']
animal_imgs = raw[raw['category']=='animal']
geometry_imgs = raw[raw['category']=='geometry']
cartoon_imgs = raw[raw['category']=='cartoon']
scales_imgs = raw[raw['category']=='scales']
chevron_imgs = raw[raw['category']=='chevron']
letternumb_imgs = raw[raw['category']=='letter_numb']
houndstooth_imgs = raw[raw['category']=='houndstooth']
stars_imgs = raw[raw['category']=='stars']
skull_imgs = raw[raw['category']=='skull']

(19, 4)

In [45]:
plain_imgs

,_unit_id,category,category:confidence,image_url
1,851505459,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
3,851505461,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
6,851505464,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
7,851505465,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
9,851505467,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
11,851505469,plain,0.6721,http://s3-eu-west-1.amazonaws.com/we-attribute...
12,851505470,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15,851505473,plain,0.3535,http://s3-eu-west-1.amazonaws.com/we-attribute...
16,851505474,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
21,851505479,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
23,851505481,plain,0.3636,http://s3-eu-west-1.amazonaws.com/we-attribute...
24,851505482,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
28,851505486,plain,0.6566,http://s3-eu-west-1.amazonaws.com/we-attribute...
31,851505489,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
37,851505496,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
38,851505497,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
42,851505501,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
44,851505503,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
45,851505504,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
47,851505506,plain,0.6495,http://s3-eu-west-1.amazonaws.com/we-attribute...
48,851505507,plain,0.6863,http://s3-eu-west-1.amazonaws.com/we-attribute...
50,851505509,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
53,851505512,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
54,851505513,plain,0.6804,http://s3-eu-west-1.amazonaws.com/we-attribute...
60,851505519,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
62,851505521,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
64,851505523,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
70,851505529,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
72,851505531,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
74,851505533,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
...,...,...,...,...
15621,851521355,plain,0.6838,http://s3-eu-west-1.amazonaws.com/we-attribute...
15623,851521357,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15624,851521358,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15626,851521360,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15628,851521362,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15629,851521363,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15630,851521364,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15633,851521434,plain,0.9174,http://s3-eu-west-1.amazonaws.com/we-attribute...
15635,851521600,plain,0.8473,http://s3-eu-west-1.amazonaws.com/we-attribute...
15639,851522438,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15641,851522601,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15644,851522844,plain,0.9597,http://s3-eu-west-1.amazonaws.com/we-attribute...
15646,851522959,plain,0.9185,http://s3-eu-west-1.amazonaws.com/we-attribute...
15648,851523030,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15652,851523107,plain,0.9208,http://s3-eu-west-1.amazonaws.com/we-attribute...
15653,851523141,plain,0.9208,http://s3-eu-west-1.amazonaws.com/we-attribute...
15655,851523202,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15657,851523237,plain,0.8932,http://s3-eu-west-1.amazonaws.com/we-attribute...
15660,851523272,plain,0.9601,http://s3-eu-west-1.amazonaws.com/we-attribute...
15668,851523400,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15669,851523472,plain,0.9665,http://s3-eu-west-1.amazonaws.com/we-attribute...
15671,851523622,plain,0.9664,http://s3-eu-west-1.amazonaws.com/we-attribute...
15672,851523794,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15678,851524399,plain,0.4060,http://s3-eu-west-1.amazonaws.com/we-attribute...
15683,851524726,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15686,851524991,plain,0.9204,http://s3-eu-west-1.amazonaws.com/we-attribute...
15688,851525187,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...
15692,851525742,plain,0.9646,http://s3-eu-west-1.amazonaws.com/we-attribute...
15695,851567928,plain,0.9232,http://s3-eu-west-1.amazonaws.com/we-attribute...
15697,854497210,plain,1.0000,http://s3-eu-west-1.amazonaws.com/we-attribute...